DROP TABLE COMIDAS CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTES CASCADE CONSTRAINTS;
DROP TABLE COMIDAS_INGREDIENTES CASCADE CONSTRAINTS;


CREATE TABLE INGREDIENTES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_del_ingrediente VARCHAR2(200) NOT NULL
);

CREATE TABLE COMIDAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(200) NOT NULL
);

CREATE TABLE COMIDAS_INGREDIENTES(
    id_comida NUMBER REFERENCES COMIDAS(id),
    id_ingrediente NUMBER REFERENCES INGREDIENTES(id)
);

INSERT INTO INGREDIENTES(NOMBRE_DEL_INGREDIENTE) VALUES ('Lechuga');
INSERT INTO INGREDIENTES(NOMBRE_DEL_INGREDIENTE) VALUES ('TOMATE');
INSERT INTO INGREDIENTES(NOMBRE_DEL_INGREDIENTE) VALUES ('CARNE');
INSERT INTO INGREDIENTES(NOMBRE_DEL_INGREDIENTE) VALUES ('PAPAS');

COMMIT;


INSERT INTO COMIDAS(nombre) VALUES ('BigMac');
INSERT INTO COMIDAS(nombre) VALUES ('Fideos');
INSERT INTO COMIDAS(nombre) VALUES ('Porotos');
INSERT INTO COMIDAS(nombre) VALUES ('Charquican');
INSERT INTO COMIDAS(nombre) VALUES ('Pastel de Papás');
COMMIT;


INSERT INTO COMIDAS_INGREDIENTES(id_comida, id_ingrediente) VALUES (1, 1);
INSERT INTO COMIDAS_INGREDIENTES(id_comida, id_ingrediente) VALUES (1, 2);
INSERT INTO COMIDAS_INGREDIENTES(id_comida, id_ingrediente) VALUES (1, 3);
INSERT INTO COMIDAS_INGREDIENTES(id_comida, id_ingrediente) VALUES (4, 3);
INSERT INTO COMIDAS_INGREDIENTES(id_comida, id_ingrediente) VALUES (4, 4);
COMMIT;


x