DROP TABLE MARCAS CASCADE CONSTRAINT;
DROP TABLE FAMILIA CASCADE CONSTRAINT;
DROP TABLE ALMACEN CASCADE CONSTRAINT;
DROP TABLE CLIENTES CASCADE CONSTRAINT;
DROP TABLE PAIS CASCADE CONSTRAINT;
DROP TABLE ESTADO_ENVIO CASCADE CONSTRAINT;
DROP TABLE METODO_PAGO CASCADE CONSTRAINT;
DROP TABLE PROVEEDOR_ENVIO CASCADE CONSTRAINT;
DROP TABLE PRODUCTOS CASCADE CONSTRAINT;
DROP TABLE STOCK_ALMACEN CASCADE CONSTRAINT;

-- Esto es un comentario

CREATE TABLE MARCAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE FAMILIA(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL
);



CREATE TABLE ALMACEN(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE CLIENTES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL
);


CREATE TABLE PAIS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE ESTADO_ENVIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE METODO_PAGO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);


CREATE TABLE PROVEEDOR_ENVIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    telefono VARCHAR2(20) NOT NULL
);

-- CREAR TABLAS CON DEPENDECIAS 1 N

CREATE TABLE PRODUCTOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    id_marca NUMBER REFERENCES MARCAS(id)
);

CREATE TABLE STOCK_ALMACEN(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    stock NUMBER(7) NOT NULL,
    fecha_rebasstecimiento TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    stock_minimo NUMBER(3) NOT NULL,
    id_almacen NUMBER REFERENCES ALMACEN(id),
    id_producto NUMBER REFERENCES PRODUCTOS(id)
);

-- Tablas sin dependencias

-- MARCAS
INSERT INTO MARCAS (nombre) VALUES ('Samsung');
INSERT INTO MARCAS (nombre) VALUES ('Apple');
INSERT INTO MARCAS (nombre) VALUES ('Sony');
INSERT INTO MARCAS (nombre) VALUES ('LG');
INSERT INTO MARCAS (nombre) VALUES ('Huawei');

-- FAMILIA
INSERT INTO FAMILIA (nombre) VALUES ('Electrónica');
INSERT INTO FAMILIA (nombre) VALUES ('Electrodomésticos');
INSERT INTO FAMILIA (nombre) VALUES ('Computación');
INSERT INTO FAMILIA (nombre) VALUES ('Telefonía');
INSERT INTO FAMILIA (nombre) VALUES ('Videojuegos');

-- ALMACEN
INSERT INTO ALMACEN (nombre) VALUES ('Central Santiago');
INSERT INTO ALMACEN (nombre) VALUES ('Bodega Norte');
INSERT INTO ALMACEN (nombre) VALUES ('Sucursal Viña del Mar');
INSERT INTO ALMACEN (nombre) VALUES ('Sucursal Concepción');
INSERT INTO ALMACEN (nombre) VALUES ('Depósito Temuco');

-- CLIENTES
INSERT INTO CLIENTES (nombre) VALUES ('Juan Pérez');
INSERT INTO CLIENTES (nombre) VALUES ('María González');
INSERT INTO CLIENTES (nombre) VALUES ('Carlos Rivas');
INSERT INTO CLIENTES (nombre) VALUES ('Ana Soto');
INSERT INTO CLIENTES (nombre) VALUES ('Pedro Morales');

-- PAIS
INSERT INTO PAIS (nombre) VALUES ('Chile');
INSERT INTO PAIS (nombre) VALUES ('Argentina');
INSERT INTO PAIS (nombre) VALUES ('Perú');
INSERT INTO PAIS (nombre) VALUES ('Brasil');
INSERT INTO PAIS (nombre) VALUES ('México');

-- ESTADO_ENVIO
INSERT INTO ESTADO_ENVIO (nombre) VALUES ('Pendiente');
INSERT INTO ESTADO_ENVIO (nombre) VALUES ('En tránsito');
INSERT INTO ESTADO_ENVIO (nombre) VALUES ('Entregado');
INSERT INTO ESTADO_ENVIO (nombre) VALUES ('Devuelto');
INSERT INTO ESTADO_ENVIO (nombre) VALUES ('Cancelado');

-- METODO_PAGO
INSERT INTO METODO_PAGO (nombre) VALUES ('Tarjeta de crédito');
INSERT INTO METODO_PAGO (nombre) VALUES ('Transferencia bancaria');
INSERT INTO METODO_PAGO (nombre) VALUES ('Efectivo');
INSERT INTO METODO_PAGO (nombre) VALUES ('PayPal');
INSERT INTO METODO_PAGO (nombre) VALUES ('Criptomoneda');

-- PROVEEDOR_ENVIO
INSERT INTO PROVEEDOR_ENVIO (nombre, telefono) VALUES ('Correos de Chile', '+56 2 600 950 2020');
INSERT INTO PROVEEDOR_ENVIO (nombre, telefono) VALUES ('Chilexpress', '+56 2 600 200 0102');
INSERT INTO PROVEEDOR_ENVIO (nombre, telefono) VALUES ('Starken', '+56 2 600 200 0111');
INSERT INTO PROVEEDOR_ENVIO (nombre, telefono) VALUES ('Bluexpress', '+56 2 2345 6789');
INSERT INTO PROVEEDOR_ENVIO (nombre, telefono) VALUES ('DHL', '+56 2 2599 8888');


-- Inderts de las tablas con dependecia
-- PRODUCTOS (depende de MARCAS)
INSERT INTO PRODUCTOS (nombre, id_marca) VALUES ('Smartphone Galaxy S23', 1);
INSERT INTO PRODUCTOS (nombre, id_marca) VALUES ('iPhone 15', 2);
INSERT INTO PRODUCTOS (nombre, id_marca) VALUES ('Televisor Bravia 55"', 3);
INSERT INTO PRODUCTOS (nombre, id_marca) VALUES ('Refrigerador InstaView', 4);
INSERT INTO PRODUCTOS (nombre, id_marca) VALUES ('Tablet MatePad Pro', 5);

-- STOCK_ALMACEN (depende de ALMACEN y PRODUCTOS)
INSERT INTO STOCK_ALMACEN (stock, stock_minimo, id_almacen, id_producto)
VALUES (120, 10, 1, 1);

INSERT INTO STOCK_ALMACEN (stock, stock_minimo, id_almacen, id_producto)
VALUES (85, 5, 2, 2);

INSERT INTO STOCK_ALMACEN (stock, stock_minimo, id_almacen, id_producto)
VALUES (45, 3, 3, 3);

INSERT INTO STOCK_ALMACEN (stock, stock_minimo, id_almacen, id_producto)
VALUES (60, 4, 4, 4);

INSERT INTO STOCK_ALMACEN (stock, stock_minimo, id_almacen, id_producto)
VALUES (30, 2, 5, 5);

COMMIT;



--Diferencia entre esto
SELECT * FROM STOCK_ALMACEN;


--Y esto
SELECT 
    sa.id AS id_stock,
    a.nombre AS nombre_almacen,
    p.nombre AS nombre_producto,
    sa.stock,
    sa.stock_minimo,
    sa.fecha_rebasstecimiento
FROM STOCK_ALMACEN sa
JOIN ALMACEN a 
    ON sa.id_almacen = a.id
JOIN PRODUCTOS p 
    ON sa.id_producto = p.id;
