DROP TABLE MARCAS CASCADE CONSTRAINT;
DROP TABLE FAMILIA CASCADE CONSTRAINT;
-- Esto es un comentario

CREATE TABLE MARCAS(
    id NUMBER PRIMARY KEY, 
    nombre VARCHAR2(50) NOT NULL
);

--Vamos a insertar una marc
INSERT INTO MARCAS(id, nombre) VALUES (1, 'SONY');
COMMIT;

INSERT INTO MARCAS(id, nombre) VALUES(2, 'LG');
COMMIT;


CREATE TABLE FAMILIA(
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL
);

INSERT INTO FAMILIA(ID, NOMBRE) VALUES (1,'ELECTRONICOS');
COMMIT;

SELECT * FROM FAMILIA;



