--Eliminamos todas las tablas
DROP TABLE MARCAS CASCADE CONSTRAINT;
DROP TABLE FAMILIAS CASCADE CONSTRAINT;
DROP TABLE PAIS CASCADE CONSTRAINT;
DROP TABLE PROVEEDOR_ENVIO CASCADE CONSTRAINT;
DROP TABLE ALMACENES CASCADE CONSTRAINT;
DROP TABLE CLIENTES CASCADE CONSTRAINT;
DROP TABLE METODO_PAGO CASCADE CONSTRAINT;
DROP TABLE ESTADO_ENVIO CASCADE CONSTRAINT;
DROP TABLE PRODUCTOS CASCADE CONSTRAINT;
DROP TABLE REGIONES CASCADE CONSTRAINT;

-- Primero vamos a crear tablas con prioridad 0
CREATE TABLE MARCAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    descripcion VARCHAR(200)
);

CREATE TABLE FAMILIAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);


CREATE TABLE PAIS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30) NOT NULL UNIQUE
);

CREATE TABLE PROVEEDOR_ENVIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30) NOT NULL UNIQUE,
    telefono VARCHAR2(12) NOT NULL
);

CREATE TABLE ALMACENES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30) NOT NULL
);

CREATE TABLE CLIENTES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30) NOT NULL,
    rut VARCHAR2(12) NOT NULL UNIQUE,
    telefono VARCHAR2(12) NOT NULL
);


CREATE TABLE METODO_PAGO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30) NOT NULL UNIQUE
);

CREATE TABLE ESTADO_ENVIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30) NOT NULL UNIQUE
);


--CREAR TODAS LAS TABLAS QUE TIENEN DEPENDENCIA 1 es a N

CREATE TABLE PRODUCTOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(200) NOT NULL,
    id_marca NUMBER NOT NULL REFERENCES MARCAS(id)
);



CREATE TABLE REGIONES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)  NOT NULL UNIQUE,
    id_pais NUMBER REFERENCES PAIS(id) NOT NULL
);

CREATE TABLE CIUDADES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)  NOT NULL UNIQUE,
    id_region NUMBER REFERENCES REGIONES(id) NOT NULL
);

CREATE TABLE COMUNAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)  NOT NULL UNIQUE,
    id_ciudad NUMBER REFERENCES CIUDADES(id) NOT NULL
);

CREATE TABLE DIRECCIONES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    calle VARCHAR2(200) NOT NULL,
    numero VARCHAR2(6) NOT NULL,
    id_comuna NUMBER REFERENCES COMUNAS(id) NOT NULL
);

CREATE TABLE ENVIOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fecha_despacho DATE NOT NULL,
    fecha_entrega TIMESTAMP DEFAULT SYSTIMESTAMP,
    id_estado_envio NUMBER REFERENCES ESTADO_ENVIO(id) NOT NULL,
    id_proveedor_envio NUMBER REFERENCES PROVEEDOR_ENVIO(id) NOT NULL
);

CREATE TABLE PAGO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fecha_pago TIMESTAMP DEFAULT SYSTIMESTAMP, 
    id_metodo_pago NUMBER REFERENCES METODO_PAGO(id) NOT NULL
);

CREATE TABLE PEDIDOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fecha_pedido TIMESTAMP DEFAULT SYSTIMESTAMP,
    id_cliente NUMBER REFERENCES CLIENTES(id) NOT NULL,
    id_envio NUMBER REFERENCES ENVIOS(id) NOT NULL,
    id_pago NUMBER REFERENCES PAGO(id) NOT NULL
);


CREATE TABLE STOCK_ALMACEN(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    stock NUMBER(7) NOT NULL,
    fecha_rebaastecimiento DATE,
    stock_minimo NUMBER(7) NOT NULL,
    id_producto NUMBER REFERENCES PRODUCTOS(id) NOT NULL,
    id_almacen NUMBER REFERENCES ALMACENES(id) NOT NULL
);


--PIVOTES
CREATE TABLE PRODUCTOS_PEDIDOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_producto NUMBER REFERENCES PRODUCTOS(id) NOT NULL,
    id_pedido NUMBER REFERENCES PEDIDOS(id) NOT NULL,
    cantidad NUMBER(3) NOT NULL
);

CREATE TABLE PRODUCTOS_PEDIDOS(
    id_producto NUMBER REFERENCES PRODUCTOS(id) NOT NULL,
    id_pedido NUMBER REFERENCES PEDIDOS(id) NOT NULL
);




INSERT INTO PAIS(nombre) values ('Chile');

INSERT INTO REGIONES(nombre, id_pais) VALUES ('Los lagos', 1);
INSERT INTO REGIONES(nombre) VALUES ('Los rios');

commit;

SELECT * FROM REGIONES;