--Las que no tienen dependencioas
-- Pais, CLIENTES ESTADO_MANTENIMIENTO, CARGOS, TIPO_MAQUINA, TIPO_SUSCRIPCION, METODO_PAGO, PROMPCIONEs, ESTADO_SUSCRIPCION

CREATE TABLE PAIS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE CLIENTES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    rut VARCHAR2(50) NOT NULL,
    nombre VARCHAR2(50) NOT NULL,
    apellido VARCHAR2(50) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    telefono VARCHAR2(50),
    fecha_nacimiento DATE NOT NULL
);

CREATE TABLE ESTADO_MANTENIMIENTO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE CARGOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    descripcion VARCHAR2(200),
    salario_base NUMBER(8) NOT NULL
);

CREATE TABLE TIPO_MAQUINA(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    categoria VARCHAR2(50) NOT NULL,
    descripcion VARCHAR2(200) NOT NULL
);


CREATE TABLE TIPO_SUSCRIPCION(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    duracion_dias NUMBER(3) NOT NULL,
    precio NUMBER(5) NOT NULL,
    descripcion VARCHAR2(200)
);

CREATE TABLE METODO_PAGO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    descripcion VARCHAR2(50)
);

CREATE TABLE PROMOCIONES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    descripcion VARCHAR2(50) NOT NULL,
    descuento_porcentaje VARCHAR2(50) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    activa CHAR(1) DEFAULT  'F'
);


CREATE TABLE ESTADO_SUSCRIPCION(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

-- Las tablas que tienen dependencias 1 N

--REGIOnm, ciudades, sucursales

CREATE TABLE REGIONES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    id_pais NUMBER REFERENCES PAIS(id) NOT NULL
);
