DROP TABLE COMIDAS CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTES CASCADE CONSTRAINTS;
DROP TABLE COMIDA_INGREDIENTES CASCADE CONSTRAINTS;


CREATE TABLE INGREDIENTES(
    id NUMBER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_del_ingrediente VARCHAR2(200) NOT NULL
);

CREATE TABLE COMIDAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(200) NOT NULL
);


CREATE TABLE COMIDA_INGREDIENTES(
    id_comida NUMBER REFERENCES COMIDAS(id),
    id_ingrediente NUMBER REFERENCES INGREDIENTES(id)
);


INSERT INTO INGREDIENTES(NOMBRE_DEL_INGREDIENTE) VALUES ('Lechuga');
INSERT INTO INGREDIENTES(NOMBRE_DEL_INGREDIENTE) VALUES ('TOMATE');
INSERT INTO INGREDIENTES(NOMBRE_DEL_INGREDIENTE) VALUES ('PAPAS');
INSERT INTO INGREDIENTES(NOMBRE_DEL_INGREDIENTE) VALUES ('ZAPALLO');
INSERT INTO INGREDIENTES(NOMBRE_DEL_INGREDIENTE) VALUES ('CARNE');
INSERT INTO INGREDIENTES(NOMBRE_DEL_INGREDIENTE) VALUES ('ZANAHORIA');
INSERT INTO INGREDIENTES(NOMBRE_DEL_INGREDIENTE) VALUES ('CHOCLO');

INSERT INTO COMIDAS(nombre) VALUES ('HAMBURGUESA');
INSERT INTO COMIDAS(nombre) VALUES ('CHACARERO');
INSERT INTO COMIDAS(nombre) VALUES ('LOMO CON LECHUGA');
INSERT INTO COMIDAS(nombre) VALUES ('BIG MAC');
INSERT INTO COMIDAS(nombre) VALUES ('FIDEOS');
INSERT INTO COMIDAS(nombre) VALUES ('CAZUELA');
INSERT INTO COMIDAS(nombre) VALUES ('HUMITAS');

COMMIT;

INSERT INTO COMIDA_INGREDIENTES(id_comida, id_ingrediente) VALUES(1,1);
INSERT INTO COMIDA_INGREDIENTES(id_comida, id_ingrediente) VALUES(1,2);
INSERT INTO COMIDA_INGREDIENTES(id_comida, id_ingrediente) VALUES(1,5);
INSERT INTO COMIDA_INGREDIENTES(id_comida, id_ingrediente) VALUES(6,3);
INSERT INTO COMIDA_INGREDIENTES(id_comida, id_ingrediente) VALUES(6,4);
INSERT INTO COMIDA_INGREDIENTES(id_comida, id_ingrediente) VALUES(6,5);
INSERT INTO COMIDA_INGREDIENTES(id_comida, id_ingrediente) VALUES(6,6);

COMMIT;


SELECT 
    c.id AS id_comida,
    c.nombre AS comida,
    i.id AS id_ingrediente,
    i.nombre_del_ingrediente AS ingrediente
FROM COMIDAS c
JOIN COMIDA_INGREDIENTES ci
    ON c.id = ci.id_comida
JOIN INGREDIENTES i
    ON i.id = ci.id_ingrediente
ORDER BY c.id, i.id;
