--Todos los drops
DROP TABLE MARCAS;
DROP TABLE FAMILIAS;
DROP TABLE CLIENTES;


--los copmentarios no se interpetan
--Vamos a crear la tabla MArcas

CREATE TABLE MARCAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE FAMILIAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE CLIENTES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(250) NOT NULL UNIQUE,
    rut VARCHAR2(12) NOT NULL,
    telefono VARCHAR2(12) NOT NULL
);

CREATE TABLE ESTADO_ENVIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE PAIS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE METODO_PAGO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE ALMACENES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE PROVEEDOR_ENVIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

--Tablas que faltan: -Estado_envio.  -Pais.   -Metodo_pago.  -Almacen.  -PROVEEDOR_ENVIO




--Creemos las tablas don dependencia


INSERT INTO CLIENTES(nombre, email) VALUES ('Carlitos', 'c@gmail.com');
COMMIT;
INSERT INTO CLIENTES(nombre, email) VALUES ('Marito', 'm@gmail.com');
COMMIT;
INSERT INTO CLIENTES(nombre, email) VALUES ('Carlitos Pepito', 'cp@gmail.com');
COMMIT;


INSERT INTO FAMILIAS(nombre) VALUES ('Electronicos');
INSERT INTO FAMILIAS(nombre) VALUES ('Hogar y cocina');
INSERT INTO FAMILIAS(nombre) VALUES ('Baño');
INSERT INTO FAMILIAS(nombre) VALUES ('Otra categoria');
COMMIT;