--Todos los drops
DROP TABLE MARCAS;
DROP TABLE FAMILIAS;
DROP TABLE CLIENTES;
DROP TABLE ESTADO_ENVIO;
DROP TABLE PAIS;
DROP TABLE METODO_PAGO;
DROP TABLE ALMACENES;
DROP TABLE PROVEEDOR_ENVIO;
DROP TABLE PRODUCTOS;


--los copmentarios no se interpetan
--Vamos a crear la tabla MArcas

CREATE TABLE MARCAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE FAMILIAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE CLIENTES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(250) NOT NULL UNIQUE,
    rut VARCHAR2(12) NOT NULL,
    telefono VARCHAR2(12) NOT NULL
);

CREATE TABLE ESTADO_ENVIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE PAIS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE METODO_PAGO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE ALMACENES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE PROVEEDOR_ENVIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

--Tablas que si tienen dependencias (1:N)
CREATE TABLE PRODUCTOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    id_marca NUMBER REFERENCES MARCAS(id) NOT NULL
);




CREATE TABLE REGIONES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    id_pais NUMBER REFERENCES PAIS(id) NOT NULL
);


CREATE TABLE CIUDADES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50),
    id_region NUMBER REFERENCES REGIONES(id) NOT NULL
);


CREATE TABLE COMUNAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50),
    id_ciudad NUMBER REFERENCES CIUDADES(id) NOT NULL
);

CREATE TABLE DIRECCIONES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    calle VARCHAR2(50) NOT NULL,
    numero VARCHAR2(10) NOT NULL, --Los chicos me dicen de    que hay casas con letras
    es_dpto CHAR(1),
    id_comuna NUMBER REFERENCES COMUNAS(id) NOT NULL
);

DROP TABLE PEDIDOS;
CREATE TABLE PEDIDOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fecha_pedido TIMESTAMP DEFAULT SYSTIMESTAMP,
    bla VARCHAR2(29)
);

INSERT INTO PEDIDOS(bla) VALUES ('bla bla');
commit;

SELECT * FROM PEDIDOS;

