DROP TABLE COMIDAS CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTES CASCADE CONSTRAINTS;



CREATE TABLE INGREDIENTES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE COMIDAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);


CREATE TABLE COMIDA_INGREDIENTE(
    id_comida        NUMBER REFERENCES COMIDAS(id),
    id_ingrediente NUMBER REFERENCES INGREDIENTES(id)
);

INSERT INTO INGREDIENTES(nombre) VALUES ('Papa');
INSERT INTO INGREDIENTES(nombre) VALUES ('Carne');
INSERT INTO INGREDIENTES(nombre) VALUES ('Queso');
INSERT INTO INGREDIENTES(nombre) VALUES ('LECHUGA');
INSERT INTO INGREDIENTES(nombre) VALUES ('TOMATE');
INSERT INTO INGREDIENTES(nombre) VALUES ('ACEITUNA');
INSERT INTO INGREDIENTES(nombre) VALUES ('Salsa de Tomate');
COMMIT;


INSERT INTO COMIDAS(nombre) VALUES ('Pastel de papas');
INSERT INTO COMIDAS(nombre) VALUES ('Lazagna');
INSERT INTO COMIDAS(nombre) VALUES ('Fideos');
INSERT INTO COMIDAS(nombre) VALUES ('Cazuela');
INSERT INTO COMIDAS(nombre) VALUES ('Hamburguesa');
COMMIT;


INSERT INTO COMIDA_INGREDIENTE(id_comida, id_ingrediente) VALUES (1,1);
INSERT INTO COMIDA_INGREDIENTE(id_comida, id_ingrediente) VALUES (1,2);
INSERT INTO COMIDA_INGREDIENTE(id_comida, id_ingrediente) VALUES (1,3);
INSERT INTO COMIDA_INGREDIENTE(id_comida, id_ingrediente) VALUES (1,6);
INSERT INTO COMIDA_INGREDIENTE(id_comida, id_ingrediente) VALUES (5,2);
INSERT INTO COMIDA_INGREDIENTE(id_comida, id_ingrediente) VALUES (5,3);
INSERT INTO COMIDA_INGREDIENTE(id_comida, id_ingrediente) VALUES (5,4);
INSERT INTO COMIDA_INGREDIENTE(id_comida, id_ingrediente) VALUES (5,5);
COMMIT;


SELECT * FROM COMIDAS;
SELECT * FROM INGREDIENTES;

SELECT * FROM COMIDA_INGREDIENTE;


SELECT 
    c.nombre AS comida,
    LISTAGG(i.nombre, ', ') WITHIN GROUP (ORDER BY i.nombre) AS ingredientes
FROM COMIDAS c
LEFT JOIN COMIDA_INGREDIENTE ci  ON c.id = ci.id_comida
LEFT JOIN INGREDIENTES i         ON i.id = ci.id_ingrediente
GROUP BY c.nombre
ORDER BY c.nombre;
