DROP TABLE MARCAS CASCADE CONSTRAINT;

-- Este es un comentario
-- Vamos a comenxar creando la tabla MARCAS

CREATE TABLE MARCAS(
    id NUMBER PRIMARY KEY,
    nombre VARCHAR2(50)  NOT NULL
);


INSERT INTO MARCAS(id, nombre) VALUES (1, 'Nike');
COMMIT;

INSERT INTO MARCAS(id) VALUES (2);
COMMIT;

CREATE TABLE FAMILIAS(
id NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(50) NOT NULL
);
INSERT INTO FAMILIAS (id, NOMBRE) VALUES(1, 'Sopaipilla :v');
COMMIT;