-- Primero eliminamos todas las tablas
DROP TABLE MARCAS CASCADE CONSTRAINT;
DROP TABLE FAMILIAS CASCADE CONSTRAINT;
DROP TABLE ESTADO_ENVIO CASCADE CONSTRAINT;
DROP TABLE PAIS CASCADE CONSTRAINT;
DROP TABLE ALMACENES CASCADE CONSTRAINT;
DROP TABLE PROVEEDOR_ENVIOS CASCADE CONSTRAINT;
DROP TABLE METODO_PAGO CASCADE CONSTRAINT;
DROP TABLE CLIENTES CASCADE CONSTRAINT;

-- Este es un comentario
-- Vamos a comenxar creando la tabla MARCAS

CREATE TABLE MARCAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)  NOT NULL
);

CREATE TABLE FAMILIAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE ESTADO_ENVIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE PAIS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE ALMACENES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE PROVEEDOR_ENVIOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    telefono VARCHAR2(12) NOT NULL
);

CREATE TABLE METODO_PAGO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE CLIENTES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    rut VARCHAR2(12) NOT NULL,
    telefono VARCHAR(12) NOT NULL
);

-- Ahora crearemos las tablas que tienen dependencia.ALTER

DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;
CREATE TABLE PRODUCTOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(250) NOT NULL,
    id_marca NUMBER NOT NULL REFERENCES MARCAS(id)
);

INSERT INTO PRODUCTOS(nombre, id_marca) VALUES ('Play Station 6', 1);
INSERT INTO PRODUCTOS(nombre, id_marca) VALUES ('TV 32', 2);
COMMIT;


SELECT * FROM PRODUCTOS;