-- Primero eliminamos todas las tablas
DROP TABLE MARCAS CASCADE CONSTRAINTS;
DROP TABLE FAMILIAS CASCADE CONSTRAINTS;
DROP TABLE ESTADO_ENVIO CASCADE CONSTRAINTS;
DROP TABLE PAIS CASCADE CONSTRAINTS;
DROP TABLE ALMACENES CASCADE CONSTRAINTS;
DROP TABLE PROVEEDOR_ENVIOS CASCADE CONSTRAINTS;
DROP TABLE METODO_PAGO CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
-- 1 n
DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;

-- Este es un comentario
-- Vamos a comenxar creando la tabla MARCAS

CREATE TABLE MARCAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50)  NOT NULL
);

CREATE TABLE FAMILIAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE ESTADO_ENVIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE PAIS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE ALMACENES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE PROVEEDOR_ENVIOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    telefono VARCHAR2(12) NOT NULL
);

CREATE TABLE METODO_PAGO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE CLIENTES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    rut VARCHAR2(12) NOT NULL,
    telefono VARCHAR(12) NOT NULL
);

-- Ahora crearemos las tablas que tienen dependencia.ALTER


CREATE TABLE PRODUCTOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(250) NOT NULL,
    id_marca NUMBER NOT NULL REFERENCES MARCAS(id)
);


