DROP TABLE MARCAS CASCADE CONSTRAINTS;
DROP TABLE FAMILIA CASCADE CONSTRAINTS;
DROP TABLE ALMACENES CASCADE CONSTRAINTS;
DROP TABLE ESTADO_ENVIO CASCADE CONSTRAINTS;
DROP TABLE PROVEEDOR_ENVIO CASCADE CONSTRAINTS;
DROP TABLE PAIS CASCADE CONSTRAINTS;
DROP TABLE METODO_PAGO CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;


CREATE TABLE MARCAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE FAMILIAS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE ALMACENES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

CREATE TABLE ESTADO_ENVIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE PROVEEDOR_ENVIO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    telefono NUMBER(11) NOT NULL
);

CREATE TABLE PAIS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE METODO_PAGO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE CLIENTES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    rut VARCHAR(12) NOT NULL,
    telefono NUMBER(11) NOT NULL
);


--Tablas con dependecia

CREATE TABLE PRODUCTOS(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(250) NOT NULL,
    id_marca NUMBER REFERENCES MARCAS(id)
);

CREATE TABLE REGIONES(
    id number GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    id_pais NUMBER REFERENCES PAIS(id) NOT NULL
);

CREATE TABLE CIUDADES(
    id number GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    id_region NUMBER REFERENCES REGIONES(id) NOT NULL
);

CREATE TABLE COMUNAS(
    id number GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    id_ciudad NUMBER REFERENCES CIUDADES(id) NOT NULL
);

CREATE TABLE DIRECCIONES(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    calle VARCHAR2(50) NOT NULL,
    numero NUMBER(5) NOT NULL,
    id_comunas NUMBER REFERENCES COMUNAS(id) NOT NULL
);


CREATE TABLE PAGO(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fecha_pago TIMESTAMP DEFAULT SYSTIMESTAMP,
    id_metodo_pago NUMBER REFERENCES METODO_PAGO(id)
);

--PIVOTES

CREATE TABLE PRODCUTO_FAMILIA(
    id_producto  NUMBER REFERENCES PRODUCTOS(id),
    id_familia NUMBER REFERENCES FAMILIAS(id)
);